### ISSUE TITLE
FEAT: automatically add users to a public group when they create a matrix account

### ISSUE THREAD

**Issue by fplord** [igneous-labs/omnispace#49]
For onboarding reasons -- we don't want people to have to bridge their Tele/Discord in order to engage with the game world.

When users join they should automatically be put into a hello-world-0 public group so we can already start chatting to them there

**Comment by fplord** [comment]
> For onboarding reasons -- we don't want people to have to bridge their Tele/Discord in order to engage with the game world.
> 
> When users join they should automatically be put into a hello-world-0 public group so we can already start chatting to them there

**Comment by f8122dac91** [comment]
There is an admin API we can use to manually invite user to a room, which is simple and I was able to write a script using it. But the problem is that since there isn't anything like registration hook that can trigger the room invitation, so this has to be ran manually. Looking into other modules in synapse.

**Comment by f8122dac91** [comment]
Oky after fucking arnd with synapse setting, managed to setup the auto-join rooms. Now I can specify an array of room addresses (e.g. `'#hello-world-0:melchior.info'`) to have every newly registered users to be automatically invited to them.

Added `#hello-world-0:melchior.info` to the list, and tested just now
